services:
  bot:
    build: .
    cpus: 0.5
    mem_limit: 512m
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /sys/class/thermal:/sys/class/thermal:ro
      - ./settings:/app/settings
      - ./assets/images:/app/assets/images
      - ./data:/app/data